main: me.mmm10.gamble.Gamble
name: Gamble
description: This plugin allows you to gamble!!!
version: 1.0
api-version: 1.15
author: MMM10
commands:
  gamble:
    description: allows you to gamble!!!
    usage: /gamble [amount] [heads or tails]
  cards:
    description: pick a card to win $$$
    usage: /cards [wager] [amount of cards] [card pick]
  slots:
    description: get 3 of the same blocks to win
    usage: /slots spin
depend: [Vault]
